# Project information
site_name: 'IoTaaP HAPI Documentation'
site_description: 'IoTaaP Hardware API Documentation'
repo_url: 'https://github.com/iotaap/docs-hapi'
nav:
  - Home: index.md
  - Device Status: deviceStatus.md
  - Websockets: websockets.md
  - OTA Update: otaUpdate.md
  - Device OTA: deviceOta.md
  - Group OTA: groupOta.md
  - HAPI Class: hapi-class.md
  - Functions: functions.md
        
copyright: 'Copyright &copy; IoTaaP'

theme: 
    name: material
    palette:
        primary: 'light-blue'
        accent: 'deep-purple'
    logo: 'images/logo.png'
    favicon: 'images/favicon.png'

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iotaap
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iotaap
      name: Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/iotaap
      name: Facebook
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCC9hU3ndh6bh-LbW3YjI98g
      name: YouTube